name: app_artventure_
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  video_player: ^2.7.0
  chewie: ^1.7.0
  device_preview: ^1.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.1.10
  youtube_explode_dart: ^1.12.4
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/